apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: josiemundi <johannasaladas@gmail.com>
    commit.image.appsody.dev/committer: GitHub <noreply@github.com>
    commit.image.appsody.dev/contextDir: /voyages-ms
    commit.image.appsody.dev/date: Mon Aug 17 10:00:50 2020 -0500
    commit.image.appsody.dev/message: Implement appsody gitops CI update actions (#64)
    commit.stack.appsody.dev/contextDir: /incubator/nodejs-express
    commit.stack.appsody.dev/date: Wed Jul 1 16:05:26 2020 +0100
    commit.stack.appsody.dev/message: 'nodejs-express: Install ca-certificates when
      building production image (#838)'
    image.opencontainers.org/created: "2020-08-17T15:09:57Z"
    image.opencontainers.org/documentation: https://github.com/ibm-cloud-architecture/refarch-kc-ms
    image.opencontainers.org/revision: 99c5fcb4ec0a1a9463d0b3fae208f7c1b0ffdfdb-modified
    image.opencontainers.org/source: https://github.com/ibm-cloud-architecture/refarch-kc-ms/tree/master
    image.opencontainers.org/url: https://github.com/ibm-cloud-architecture/refarch-kc-ms
    stack.appsody.dev/authors: Gireesh Punathil <gireeshpunathil>
    stack.appsody.dev/configured: docker.io/appsody/nodejs-express:0.4
    stack.appsody.dev/created: "2020-07-01T15:09:37Z"
    stack.appsody.dev/description: Express web framework for Node.js
    stack.appsody.dev/digest: sha256:4d62493bcc83c45665f6fc25959ba7fdc737876851796f81a110dd123bf739b0
    stack.appsody.dev/documentation: https://github.com/appsody/stacks/tree/master/incubator/nodejs-express/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 06ea2933df2b6f831fef31ddcbe24c7e0135170c
    stack.appsody.dev/source: https://github.com/appsody/stacks/tree/master/incubator/nodejs-express/image
    stack.appsody.dev/tag: docker.io/appsody/nodejs-express:0.4.13
    stack.appsody.dev/title: Node.js Express
    stack.appsody.dev/url: https://github.com/appsody/stacks/tree/master/incubator/nodejs-express
  creationTimestamp: null
  labels:
    app.appsody.dev/name: refarch-kc
    app.kubernetes.io/part-of: refarch-kc
    image.opencontainers.org/title: voyages-ms
    stack.appsody.dev/id: nodejs-express
    stack.appsody.dev/version: 0.4.13
  name: voyages-ms
spec:
  applicationImage: ibmcase/kcontainer-voyages-ms:0.1.38
  createKnativeService: false
  env:
  - name: PORT
    value: "3000"
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: brokers
        name: kafka-brokers
  - name: KCSOLUTION_ORDERS_TOPIC
    valueFrom:
      configMapKeyRef:
        key: ordersTopic
        name: kafka-topics
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: voyages-ms
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 3000
    type: NodePort
  stack: nodejs-express
  version: 1.0.0
status: {}
