bases:
  - ../base

# Event Streams truststore mounted as /config/resources/security/es-ssl/es-cert.jks

patchesStrategicMerge:
  - ./appsody-volume-mounts.yaml
  - ./appsody-volumes.yaml
  - ./service-account-patch.yaml

patchesJson6902:
  - target:
      group: openliberty.io
      version: v1beta1
      kind: OpenLibertyApplication
      name: order-command-ms
    path: ./appsody-env-patch.yaml