bases:
  - ../../../services/fleetms
  - ../../../services/kc-ui
  - ../../../services/ordercommandms
  - ../../../services/orderqueryms
  - ../../../services/reefersimulator
  - ../../../services/scoringmp
  - ../../../services/springcontainerms
  - ../../../services/voyagesms