name: Update GitOps deployments
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-gitops-deployments:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout default sandbox branch
      id: checkout-sandbox-branch
      run: |
        git checkout ${DESIRED_BRANCH}
      env:
        DESIRED_BRANCH: eda-demo/gse-eda-demos.us-east.containers.appdomain.cloud
    - name: Update GitOps YAMLs
      id: update-gitops-yamls
      uses: ibm-cloud-architecture/actions-update-gitops@master
